urlweb:           "https://hanifahreza.github.io/os211/"
urlgithub:        "https://github.com/hanifahreza/os211/"
urlghpage:        "https://hanifahreza.github.io/os211/"
keywords:         "jekyll, testing"